### ISSUE TITLE
Nếu em nhập xâu kí tự có chứa dấu cách thì nó có đọc được hết không?

### ISSUE THREAD

**Issue by linhnd99** [namkeke/JAVA_HIT_2019#1]
https://github.com/namkeke/BTVN_JAVA_2019/blob/55ad4d4b0684b5e53169feb8cd6e8563f28ac5a0/Week%202/src/bt/bai4.java#L16

**Comment by pnam16** [comment]
em nhập nextLine thì nó ko cho em nhập luôn 
phải làm như nào anh !!

**Comment by linhnd99** [comment]
nó ko cho nhập là sao? nó lỗi gì à?

**Comment by pnam16** [comment]
em nhập cái số thực xong nó ko cho em nhập xâu nữa và nó cout hết những cái có thể ra và kết thúc ctrinh
![image](https://user-images.githubusercontent.com/52752638/66743672-a2823400-eea4-11e9-9d1e-ad41d367ced5.png)

**Comment by linhnd99** [comment]
thực ra là sc.nextLine() nó sẽ nhận luôn phím enter của lần em nhập số thực, nên là em có thể code như thế này 
```
System.out.print("Nhap xau: ");
sc.nextLine();
String s = sc.nextLine();
System.out.println("Xau: " + s);
```
khi đó cái sc.nextLine() thứ nhất nó sẽ hứng phím enter, thì sẽ nhập được s

**Comment by pnam16** [comment]
ok anh e hiểu rồi
