### ISSUE TITLE
BTVN buổi 3

### ISSUE THREAD

**Issue by linhnd99** [namkeke/JAVA_HIT_2019#3]
Em có thể dùng ss+=s.charAt(i)-'0' thay vì dùng hàm cũng được đấy
https://github.com/namkeke/BTVN_JAVA_2019/blob/8aee556f6d9ee207c5c6fdb0cce60890569d1267/Week%203/src/bt/bai2.java#L13

**Comment by pnam16** [comment]
vâng anh
