### ISSUE TITLE
BTVN_Buoi3_Bai5

### ISSUE THREAD

**Issue by linhnd99** [namkeke/JAVA_HIT_2019#4]
cái n này có tác dụng gì thế em?
https://github.com/namkeke/BTVN_JAVA_2019/blob/8aee556f6d9ee207c5c6fdb0cce60890569d1267/Week%203/src/bt/bai5_1.java#L51

**Comment by pnam16** [comment]
là nhớ anh ạ

**Comment by linhnd99** [comment]
em sẽ làm gì với cái nhớ này?

**Comment by pnam16** [comment]
ban đầu nhớ bằng 0 vì em công hàng đơn vị
nếu chữ số hàng đơn vị + vào với nhau lớn hơn 9 thì biến nhớ =1 và công vào các phép hàng chụp 
hình như e code thiếu rồi :v

**Comment by pnam16** [comment]
ban đầu nhớ bằng 0 vì em công hàng đơn vị
nếu chữ số hàng đơn vị + vào với nhau lớn hơn 9 thì biến nhớ =1 và cộng vào hàng chục
else nhớ = 0

**Comment by linhnd99** [comment]
em chưa xử lí được chỗ, nếu ở lần cộng cuối cùng mà nó vẫn nhớ 1,  ví dụ như là 24+77
7+4=11 viết 1 nhớ 1 sang phiasau. thì phía sau sẽ là 7+2+1 = 10, lúc này là lần cộng cuối cùng rồi nên sẽ không %10 nữa, mà lấy cả 10 luôn

**Comment by pnam16** [comment]
em sửa và
vẫn bị như vậy anh ạ
:(
