### ISSUE TITLE
bai1

### ISSUE THREAD

**Issue by linhnd99** [namkeke/JAVA_HIT_2019#5]
Sao lại đặt hết thuộc tính là public rồi bỏ get set đi thế? :v 
https://github.com/namkeke/BTVN_JAVA_2019/blob/4883a2a700cce808944dd59b39c83046c9c8c9e0/Week%205/src/HomeWork/Bai1/Member.java#L15

**Comment by pnam16** [comment]
Vì em lười @@
Với đề cũng không yc mà anh

Vào 10:25, Th 6, 8 thg 11, 2019 Nguyen Duc Linh <notifications@github.com>
đã viết:

**Comment by linhnd99** [comment]
đặt private rồi tạo get set sẽ bảo mật dữ liệu tốt hơn, đấy là anh được học lại là như vậy, nhưng cũng chưa chứng minh được là tại sao private + get set lại bảo mật tốt hơn là public. chỉ thấy là tiện hơn ở chỗ có những thuộc tính chỉ được phép get, hoặc chỉ được phép set, cái này là public ko làm được
//anh code toàn auto private +get set :v

**Comment by pnam16** [comment]
Vâng anh :v

Vào 2:30, CN, 10 thg 11, 2019 Nguyen Duc Linh <notifications@github.com> đã
viết:
